### ISSUE TITLE
Pin Order

### ISSUE THREAD

**Issue by bboyho** [sparkfun/Speed_Trap#1]
Just a suggestion but the pin order on line 24 of the code [https://github.com/sparkfun/Speed_Trap/blob/master/firmware/SparkFun_Speed_Trap/SparkFun_Speed_Trap.ino] should read A0 -> Power Enable. I.e.) From the Arduino Pin to the LIDAR pin. =)

**Comment by nseidle** [comment]
Yep! You're right. Sound be fixed in a minute.
